/**  
* <p>Title: Test_MainMenu.java</p>  
* <p>Description: </p>    
* <p>Aplication: UNED</p>  
* @author Silverio Manuel Rosales Santana
* @date 22 sept. 2021  
* @version 1.0  
*/  
package Pruebas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




/**
 *
 * @author r.kumbara
 */
public class Test_MainMenu extends JFrame {

    /** serialVersionUID*/  
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Test_MainMenu
     */
    public Test_MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jPanel4 = new JPanel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jPanel5 = new JPanel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jPanel6 = new JPanel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jPanel7 = new JPanel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jPanel8 = new JPanel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jLabel3 = new JLabel();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 70, 78));
        jPanel2.setLayout(new AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(54, 70, 78));
        jPanel4.setLayout(new AbsoluteLayout());

        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-magazine-23.png"))); // NOI18N
        jPanel4.add(jLabel4, new AbsoluteConstraints(10, 4, 40, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Catalogs");
        jPanel4.add(jLabel5, new AbsoluteConstraints(60, 10, 140, 20));

        jPanel2.add(jPanel4, new AbsoluteConstraints(0, 70, 210, 40));

        jPanel5.setBackground(new java.awt.Color(54, 70, 78));
        jPanel5.setLayout(new AbsoluteLayout());

        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-home-page-23.png"))); // NOI18N
        jPanel5.add(jLabel6, new AbsoluteConstraints(10, 4, 40, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dashboard");
        jPanel5.add(jLabel7, new AbsoluteConstraints(60, 10, 140, 20));

        jPanel2.add(jPanel5, new AbsoluteConstraints(0, 30, 210, 40));

        jPanel6.setBackground(new java.awt.Color(54, 70, 78));
        jPanel6.setLayout(new AbsoluteLayout());

        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-male-user-23.png"))); // NOI18N
        jPanel6.add(jLabel8, new AbsoluteConstraints(10, 4, 40, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Members");
        jPanel6.add(jLabel9, new AbsoluteConstraints(60, 10, 140, 20));

        jPanel2.add(jPanel6, new AbsoluteConstraints(0, 110, 210, 40));

        jPanel7.setBackground(new java.awt.Color(54, 70, 78));
        jPanel7.setLayout(new AbsoluteLayout());

        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-increase-23.png"))); // NOI18N
        jPanel7.add(jLabel10, new AbsoluteConstraints(10, 4, 40, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Report");
        jPanel7.add(jLabel11, new AbsoluteConstraints(60, 10, 140, 20));

        jPanel2.add(jPanel7, new AbsoluteConstraints(0, 190, 210, 40));

        jPanel8.setBackground(new java.awt.Color(54, 70, 78));
        jPanel8.setLayout(new AbsoluteLayout());

        jLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-survey-23.png"))); // NOI18N
        jPanel8.add(jLabel12, new AbsoluteConstraints(10, 4, 40, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Collections");
        jPanel8.add(jLabel13, new AbsoluteConstraints(60, 10, 140, 20));

        jPanel2.add(jPanel8, new AbsoluteConstraints(0, 150, 210, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel14.setText("Blessing Software");
        jPanel2.add(jLabel14, new AbsoluteConstraints(20, 486, 160, 20));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel15.setText("Copyright @ Ricid Kumbara");
        jPanel2.add(jLabel15, new AbsoluteConstraints(20, 470, 160, -1));

        jPanel1.add(jPanel2, new AbsoluteConstraints(0, 73, 210, 552));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/Icons/icons8-menu-30.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            @Override
			public void mouseEntered(MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            @Override
			public void mouseExited(MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new AbsoluteConstraints(204, 40, 40, -1));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/Icons/FMainMenu.png"))); // NOI18N
        jPanel1.add(jLabel1, new AbsoluteConstraints(0, 0, 1000, 625));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x = 210;
    int a = 0;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if ( x == 210 ) {
            jPanel2.setSize(210, 552);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        
                        for ( int i = 210; i >= 0; i--){
                            Thread.sleep(1);
                            jPanel2.setSize(i, 552);
                            
                            a++;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            jPanel2.setSize(x, 552);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            jPanel2.setSize(i, 552);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 210;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        labelcolor(jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        resetlabelcolor(jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) { ex.printStackTrace();
        } catch (InstantiationException ex) { ex.printStackTrace();
        } catch (IllegalAccessException ex) { ex.printStackTrace();
        } catch (UnsupportedLookAndFeelException ex) { ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new Test_MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(53,162,107));
    }
    
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(54,70,78));
    }
}